apiVersion: v1
kind: Service
metadata:
  name: deploy
  labels:
    app: deploy
spec:
  type: NodePort
  selector:
    app: deploy
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080